### ISSUE TITLE
Error with config osx-vscode-debug

### ISSUE THREAD

**Issue by pjako** [floooh/fips#137]
Having some errors trying the new osx-vscode-debug config.
Here is the log:
```
➜  ngl ./fips set config osx-vscode-debug
➜  ngl ./fips gen
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DFIPS_CONFIG=osx-vscode-debug -DFIPS_USE_CCACHE=OFF -DFIPS_AUTO_IMPORT=ON -B/Users/pjako/projects/oryol/fips-build/ngl/osx-vscode-debug -H/Users/pjako/projects/oryol/ngl
=== fips_setup(PROJECT Ngl)
CMAKE_BUILD_TYPE: Debug
FIPS_ROOT_DIR: /Users/pjako/projects/oryol/fips
FIPS_PROJECT_DIR: /Users/pjako/projects/oryol/ngl
FIPS_BUILD_DIR: /Users/pjako/projects/oryol/fips-build
FIPS_DEPLOY_DIR: /Users/pjako/projects/oryol/fips-deploy
FIPS_AUTO_IMPORT: ON
Host system: OSX
CMAKE_CXX_COMPILER_ID: Clang
Detected C++ Compiler: Clang (FIPS_CLANG)
FIPS_CONFIG: osx-vscode-debug
FIPS_PROJECT_BUILD_DIR: /Users/pjako/projects/oryol/fips-build/Ngl/osx-vscode-debug
FIPS_PROJECT_DEPLOY_DIR: /Users/pjako/projects/oryol/fips-deploy/Ngl/osx-vscode-debug
FIPS_PLATFORM: OSX
FIPS_PLATFORM_NAME: osx
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pjako/projects/oryol/fips-build/ngl/osx-vscode-debug
Traceback (most recent call last):
  File "./fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/Users/pjako/projects/oryol/fips/mod/fips.py", line 49, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "/Users/pjako/projects/oryol/fips/verbs/gen.py", line 19, in run
    project.gen(fips_dir, proj_dir, cfg_name)
  File "/Users/pjako/projects/oryol/fips/mod/project.py", line 113, in gen
    if gen_project(fips_dir, proj_dir, cfg, True) :
  File "/Users/pjako/projects/oryol/fips/mod/project.py", line 84, in gen_project
    vscode.write_workspace_settings(fips_dir, proj_dir, cfg, toolchain_path, defines)
  File "/Users/pjako/projects/oryol/fips/mod/tools/vscode.py", line 87, in write_workspace_settings
    all_targets = extract_targets(codemodel, None)
  File "/Users/pjako/projects/oryol/fips/mod/tools/vscode.py", line 34, in extract_targets
    for config in codemodel['configurations']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by pjako** [comment]
Solved it myself, needed a more recent version of cmake

**Comment by floooh** [comment]
Thanks! I'll open a separate ticket to check for the required cmake version and give a better error message, this is because the new cmake-server feature is needed which is still experimental, but I also don't want to generally raise the required cmake version, only when used with the vscode stuff.
