### ISSUE TITLE
Error when setting up SDKs if previous download failed

### ISSUE THREAD

**Issue by kavika13** [floooh/fips#189]
Repro steps:
1. Setup environment (python, cmake, ninja, etc)
2. `git clone https://github.com/floooh/sokol-samples.git`
3. `cd sokol-samples`
4. `./fips setup emscripten`
5. Cancel build in middle of download with <kbd>CTRL + C</kbd>
6. `./fips setup emscripten` (again)

Expected: Previous zip download is detected as corrupt, and the download is attempted again
Actual: Previous zip download is detected as present, and python zip throws an exception that crashes fips

Error is:
```
λ fips setup emscripten
=== setup emscripten SDK:
'emsdk-portable-64bit.zip' already exists

uncompressing 'emsdk-portable-64bit.zip'...
Traceback (most recent call last):
  File "fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "C:\Users\my_user_name\development/fips\mod\fips.py", line 49, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "C:/Users/my_user_name/development/fips/verbs\setup.py", line 17, in run
    emscripten.setup(fips_dir, proj_dir)
  File "C:\Users\my_user_name\development/fips\mod\emscripten.py", line 111, in setup
    uncompress(get_archive_path(fips_dir), get_sdk_dir(fips_dir), 'emsdk-portable')
  File "C:\Users\my_user_name\development/fips\mod\emscripten.py", line 74, in uncompress
    with zipfile.ZipFile(src_path, 'r') as archive:
  File "C:\Users\my_user_name\AppData\Local\Programs\Python\Python36\lib\zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "C:\Users\my_user_name\AppData\Local\Programs\Python\Python36\lib\zipfile.py", line 1167, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by floooh** [comment]
Yeah, that's a bit unfortunate. For a quick workaround, delete the ```fips-sdks``` directory in the same directory where the fips directory is and try the ```fips setup emscripten``` again.

I'll keep the ticket open for the case that I'll get around to implement a proper fix, but it's quite low-prio at the moment.

Thanks for the bug report :)

**Comment by floooh** [comment]
...it's now possible to cleanup any old or partial emscripten SDK installs with:

```./fips emsdk uninstall```
