### ISSUE TITLE
python error with MSYS/MSYS2

### ISSUE THREAD

**Issue by floooh** [floooh/fips#194]
Mentioned in this ticket: https://github.com/floooh/sokol-samples/issues/9

KeyError: 'MSYS_NT-10.0' looks suspicious and should at least provide a better error message (even if we don't support MSYS directly):

```
Cloning into '/c/path/fips'...
remote: Counting objects: 3859, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 3859 (delta 14), reused 21 (delta 10), pack-reused 3826
Receiving objects: 100% (3859/3859), 1.39 MiB | 395.00 KiB/s, done.
Resolving deltas: 100% (2631/2631), done.
Checking out files: 100% (270/270), done.
Traceback (most recent call last):
  File "./fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/c/path/fips/mod/fips.py", line 49, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "/c/path/fips/verbs/build.py", line 18, in run
    cfg_name = settings.get(proj_dir, 'config')
  File "/c/path/fips/mod/settings.py", line 70, in get
    value = get_default(key)
  File "/c/path/fips/mod/settings.py", line 43, in get_default
    return config.get_default_config()
  File "/c/path/fips/mod/config.py", line 48, in get_default_config
    return default_config[util.get_host_platform()]
  File "/c/path/fips/mod/util.py", line 273, in get_host_platform
    return host_platforms[platform.system()]
KeyError: 'MSYS_NT-10.0'
```

**Comment by fungos** [comment]
Similar to this: https://github.com/floooh/fips/issues/128

**Comment by floooh** [comment]
@fungos ah right, that's why it looked so familiar :)
