### ISSUE TITLE
Python3 issue when checking out a 'versioned' dependency.

### ISSUE THREAD

**Issue by floooh** [floooh/fips#195]
Originally reported here: https://github.com/floooh/fips-hello-world/issues/2

When fetching fips-hello-world dependencies:

```
$ ./fips build
=== dependency: 'fips-hello-dep1':
Cloning into 'fips-hello-dep1'...
remote: Counting objects: 53, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 53 (delta 14), reused 52 (delta 14), pack-reused 0
Unpacking objects: 100% (53/53), done.
=== dependency: 'fips-hello-dep2':
Cloning into 'fips-hello-dep2'...
remote: Counting objects: 62, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 62 (delta 17), reused 62 (delta 17), pack-reused 0
Unpacking objects: 100% (62/62), done.
=== dependency: 'fips-hello-dep3':
Cloning into 'fips-hello-dep3'...
remote: Counting objects: 85, done.
remote: Total 85 (delta 0), reused 0 (delta 0), pack-reused 85
Unpacking objects: 100% (85/85), done.
=== revision: '191f59f0':
Note: checking out '191f59f0'.

You are in 'detached HEAD' state. You can look around, make experimental                                              
changes and commit them, and you can discard any commits you make in this                                             
state without impacting any branches by performing another checkout.                                                  

If you want to create a new branch to retain commits you create, you may                                              
do so (now or later) by using -b with the checkout command again. Example:                                            

  git checkout -b <new-branch-name>

HEAD is now at 191f59f First commit - working version 1
Traceback (most recent call last):
  File "./fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/home/spacepluk/hacking/fips/mod/fips.py", line 49, in run                                                    
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)                                                        
  File "/home/spacepluk/hacking/fips/verbs/build.py", line 19, in run                                                 
    project.build(fips_dir, proj_dir, cfg_name)
  File "/home/spacepluk/hacking/fips/mod/project.py", line 229, in build                                              
    dep.fetch_imports(fips_dir, proj_dir)
  File "/home/spacepluk/hacking/fips/mod/dep.py", line 228, in fetch_imports                                          
    _rec_fetch_imports(fips_dir, proj_dir, [])
  File "/home/spacepluk/hacking/fips/mod/dep.py", line 204, in _rec_fetch_imports                                     
    dep_ok = git.checkout(dep_proj_dir, git_commit)
  File "/home/spacepluk/hacking/fips/mod/tools/git.py", line 188, in checkout                                         
    return output.split(':')[0] != 'error'
TypeError: a bytes-like object is required, not 'str'
```

**Comment by spacepluk** [comment]
let me know when you have it and I'll give it a try :)

**Comment by floooh** [comment]
Alright this should be fixed now, I also found a couple of related bugs. The reason is that python3 treats byte sequences and strings as incompatible object types (e.g. subprocess.check_output() returns bytes which are processed as strings, in python2 this 'just works' in python3 it doesn't)

**Comment by floooh** [comment]
PS: associated commit: https://github.com/floooh/fips/commit/bbb76c57f307b666c0f6427b3d7ad239f814132f

**Comment by spacepluk** [comment]
Thanks! FYI the rev specified for dep3 also has some trouble with python3:

```
Traceback (most recent call last):
  File "/home/spacepluk/hacking/fips-build/fips-hello-world/linux-make-debug/fips-gen.py", line 55, in <module>
    processFile(attrs)
  File "/home/spacepluk/hacking/fips-build/fips-hello-world/linux-make-debug/fips-gen.py", line 44, in processFile
    module = imp.load_module(moduleName, fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/spacepluk/hacking/fips-hello-dep2/src/dep2/dep2.py", line 2, in <module>
    import hello_generator as gen
  File "/home/spacepluk/hacking/fips-hello-dep2/fips-generators/hello_generator.py", line 25
    print '## generating {}'.format(out_hdr)        
                           ^
SyntaxError: invalid syntax
```

**Comment by floooh** [comment]
Hmm how do I reproduce that? I was testing with ```python3 fips build``` on the fips-hello-world project, and this was running through all the way on MacOS (python version 3.7.0). I'll fix the bug nonetheless (there are parantheses missing around the print).

**Comment by floooh** [comment]
Ah ok, I think it didn't trigger since I built the project with python2 first, and when I tested with python3 the code-generator didn't run because there were no changes to the code-generation source files.

It should be fixed now, you need to run ```./fips update``` from the fips-hello-world directory, and rebuild everything.

**Comment by spacepluk** [comment]
thanks!
