### ISSUE TITLE
Included PyYaml (yaml3) breaks with python 3.10

### ISSUE THREAD

**Issue by fadeopolis** [floooh/fips#275]
Hi, 

The problem is that the code uses `collections.Hashable` instead of `collections.abc.Hashable`.
This has been deprecated since python 3.3, and 3.10 finally made it an error.

As far as I can tell this has been fixed in upstream in release 4.1 (https://github.com/yaml/pyyaml/commit/9959328b41ee577c6f14e3a0184b07dd0ecadb8c).
It's just a two line fix if you don't want to update the packaged pyyaml (`collections` --> `collections.abc`).

Btw, Thanks for this great tool and your other projects :)

Error message when building sokol-tools with fips:
```
Traceback (most recent call last):
  File ".../sokol-tools/fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File ".../fips/mod/fips.py", line 51, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File ".../fips/verbs/build.py", line 24, in run
    project.build(fips_dir, proj_dir, cfg_name, None, build_tool_args)
  File ".../fips/mod/project.py", line 241, in build
    configs = config.load(fips_dir, proj_dir, cfg_name)
  File ".../fips/mod/config.py", line 175, in load
    cfg = yaml.load(f)
  File ".../fips/yaml/yaml3/__init__.py", line 72, in load
    return loader.get_single_data()
  File ".../fips/yaml/yaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File ".../fips/yaml/yaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File ".../fips/yaml/yaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File ".../fips/yaml/yaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File ".../fips/yaml/yaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'
```

**Comment by floooh** [comment]
Ok, I have applied a manual fix, haven't tested with 3.10 though. Thanks for the bug report and investigation!
