### ISSUE TITLE
`./fips list` crashes with TypeError: 'NoneType'

### ISSUE THREAD

**Issue by samw3** [floooh/fips#295]
I'm not sure how I got into this state, but I can't do `./fips list`.  It crashes with `TypeError: 'NoneType' object is not iterable`

```
$ ./fips list
=== configs:
from /Users/samw3/prj/Play/fips/configs:
  android-make-debug
  android-make-release
...
  win64-vstudio-debug
  win64-vstudio-release
=== build-tools:
make
ninja
cmake
vscode
clion
xcodebuild
=== registry:
oryol => https://github.com/floooh/oryol.git
...
fips-nlohmann-json => https://github.com/sgerbino/fips-nlohmann-json.git
=== settings:
  config: osx-clion-debug
  target: None (default value)
  jobs: 12 (default value)
  local: off (default value)
  iosteam: None (default value)
=== exports:
project 'sokol' exports:
  header search dirs:
    .
    util
project 'sokol-tools-bin' exports:
    nothing
project 'glm' exports:
  header search dirs:
    glm
  defines:
    GLM_FORCE_RADIANS => 1
    GLM_FORCE_CTOR_INIT => 1
project 'mudgfx' exports:
    nothing
=== imports:
project 'sokol' imports:
    nothing
project 'sokol-tools-bin' imports:
    nothing
project 'glm' imports:
    nothing
project 'mudgfx' imports:
  'sokol' from 'https://github.com/floooh/sokol' at branch 'master'
  'sokol-tools-bin' from 'git@github.com:floooh/sokol-tools-bin.git' at branch 'master'
  'glm' from 'git@github.com:fips-libs/fips-glm.git' at branch 'master'
=== targets:
  config: osx-clion-debug
Traceback (most recent call last):
  File "/Users/samw3/prj/Play/mudgfx/./fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/Users/samw3/prj/Play/fips/mod/fips.py", line 49, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "/Users/samw3/prj/Play/fips/verbs/list.py", line 178, in run
    list_targets(fips_dir, proj_dir, args[1:])
  File "/Users/samw3/prj/Play/fips/verbs/list.py", line 72, in list_targets
    type_targets = [tgt for tgt in targets if targets[tgt] == type]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by samw3** [comment]
I think it might be caused by not yet having a CMakeLists.txt in src yet.

**Comment by floooh** [comment]
Thanks for the bug report!

Hmm, when I delete the CMakeLists.txt file in an existing project I get:

```
=== targets:
  config: osx-vscode-debug
  can't fetch project target list, please run 'fips gen' first!
```

From looking at the code, the only reason I can see is if the `yaml.load()` here returns a `None`:

First, can you try a different build setting like `osx-make-debug`? It's unlikely that this changes anything, but the `clion` build configs are not tested that much.

...also if you could create a Zip archive of the project directory which triggers the problem, and either attach it here or send to my email address listed in my profile (https://github.com/floooh) that would help a lot in reproducing the problem.

Thanks!

**Comment by samw3** [comment]
I was able to repro this (see below), but have also attached the resulting project dir, in case that helps. [test.zip](https://github.com/floooh/fips/files/15237518/test.zip)

`./fips clean all` does seem to "fix" it in the sense that the command completes and it asks you to run `fips gen` again.  When I do that the issue returns.

`./fips diag` has a few errors, but they are all android related.  (I'm not interested in having that environment set up right now.)

Here are the steps to repro with corresponding output:
```
samw3 Play $ mkdir test
samw3 Play $ ./fips/fips init test
wrote '/Users/samw3/prj/Play/test/CMakeLists.txt'
wrote '/Users/samw3/prj/Play/test/fips'
wrote '/Users/samw3/prj/Play/test/fips.cmd'
wrote '/Users/samw3/prj/Play/test/fips.yml'
wrote '/Users/samw3/prj/Play/test/.gitignore'
samw3 Play $ cd test
samw3 test $ ./fips gen
=== generating: osx-xcode-debug
config file: /Users/samw3/prj/Play/fips/configs/osx-xcode-debug.yml
Preset CMake variables:

  CMAKE_BUILD_TYPE="Debug"
  CMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk"
  FIPS_AUTO_IMPORT="ON"
  FIPS_CONFIG="osx-xcode-debug"
  FIPS_LOCAL_BUILD="OFF"

CMAKE_BUILD_TYPE: Debug
FIPS_ROOT_DIR: /Users/samw3/prj/Play/fips
FIPS_PROJECT_DIR: /Users/samw3/prj/Play/test
FIPS_BUILD_DIR: /Users/samw3/prj/Play/fips-build
FIPS_DEPLOY_DIR: /Users/samw3/prj/Play/fips-deploy
FIPS_PROJECT_NAME: test
FIPS_AUTO_IMPORT: ON
FIPS_CONFIG: osx-xcode-debug
FIPS_PROJECT_BUILD_DIR: /Users/samw3/prj/Play/fips-build/test/osx-xcode-debug
FIPS_PROJECT_DEPLOY_DIR: /Users/samw3/prj/Play/fips-deploy/test/osx-xcode-debug
Host system: OSX
CMAKE_CXX_COMPILER_ID: AppleClang
FIPS_CLANG: 1
FIPS_APPLE_CLANG: 1
FIPS_PLATFORM: OSX
FIPS_PLATFORM_NAME: osx
CMake Warning at /Users/samw3/prj/Play/fips/cmake/fips_deprecated.cmake:12 (message):
  !!! DEPRECATED !!! fips_finish() is deprecated, please remove the call
Call Stack (most recent call first):
  CMakeLists.txt:14 (fips_finish)


-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/samw3/prj/Play/fips-build/test/osx-xcode-debug
1 configs generated
samw3 test $ ./fips list
=== configs:
from /Users/samw3/prj/Play/fips/configs:
  android-make-debug
  android-make-release
  android-ninja-debug
  android-ninja-release
  android-vscode-debug
  android-vscode-release
  androidmips-make-debug
  androidmips-make-release
  androidmips-ninja-debug
  androidmips-ninja-release
  androidx86-make-debug
  androidx86-make-release
  androidx86-ninja-debug
  androidx86-ninja-release
  emsc-make-debug
  emsc-make-release
  emsc-ninja-debug
  emsc-ninja-release
  emsc-vscode-debug
  emsc-vscode-release
  ios-xcode-debug
  ios-xcode-release
  linux-clion-debug
  linux-clion-release
  linux-eclipse-debug
  linux-eclipse-release
  linux-make-debug
  linux-make-release
  linux-ninja-debug
  linux-ninja-release
  linux-vscode-debug
  linux-vscode-release
  osx-arm64-ninja-debug
  osx-arm64-ninja-release
  osx-clion-debug
  osx-clion-release
  osx-fat-ninja-debug
  osx-fat-ninja-release
  osx-make-debug
  osx-make-debug-arc
  osx-make-release
  osx-make-release-arc
  osx-ninja-debug
  osx-ninja-debug-arc
  osx-ninja-release
  osx-ninja-release-arc
  osx-vscode-debug
  osx-vscode-debug-arc
  osx-vscode-release
  osx-x64-ninja-debug
  osx-x64-ninja-release
  osx-x86_64-ninja-debug
  osx-x86_64-ninja-release
  osx-xcode-debug
  osx-xcode-debug-arc
  osx-xcode-release
  osx-xcode-release-arc
  raspi-make-debug
  raspi-make-release
  raspi-ninja-debug
  raspi-ninja-release
  uwp-vstudio-debug
  uwp-vstudio-release
  wasi-make-debug
  wasi-make-release
  wasi-ninja-debug
  wasi-ninja-release
  wasi-vscode-debug
  wasi-vscode-release
  wasm-make-debug
  wasm-make-release
  wasm-ninja-debug
  wasm-ninja-release
  wasm-vscode-debug
  wasm-vscode-release
  webgl2-emsc-make-debug
  webgl2-emsc-make-release
  webgl2-emsc-ninja-debug
  webgl2-emsc-ninja-release
  webgl2-wasm-ninja-release
  win32-vs2013-debug
  win32-vs2013-release
  win32-vs2015-debug
  win32-vs2015-release
  win32-vs2017-debug
  win32-vs2017-release
  win32-vstudio-debug
  win32-vstudio-release
  win64-clang-ninja-debug
  win64-clang-ninja-release
  win64-clang-vscode-debug
  win64-clang-vscode-release
  win64-vs2013-debug
  win64-vs2013-release
  win64-vs2015-debug
  win64-vs2015-release
  win64-vs2017-debug
  win64-vs2017-release
  win64-vs2019-debug
  win64-vs2019-release
  win64-vs2022-debug
  win64-vs2022-release
  win64-vscode-debug
  win64-vscode-release
  win64-vstudio-debug
  win64-vstudio-release
=== build-tools:
make
ninja
cmake
vscode
clion
xcodebuild
=== registry:
oryol => https://github.com/floooh/oryol.git
gliml => https://github.com/floooh/gliml.git
fips-glm => https://github.com/floooh/fips-glm.git
fips-unittestpp => https://github.com/floooh/fips-unittestpp.git
fips-zlib => https://github.com/floooh/fips-zlib.git
fips-glfw => https://github.com/floooh/fips-glfw.git
fips-libcurl => https://github.com/floooh/fips-libcurl.git
fips-vld => https://github.com/floooh/fips-vld.git
fips-cjson => https://github.com/floooh/fips-cjson.git
fips-cpptoml => https://github.com/floooh/fips-cpptoml.git
oryol-test-app => https://github.com/floooh/oryol-test-app.git
fips-hello-world => https://github.com/floooh/fips-hello-world.git
fips-hello-dep1 => https://github.com/floooh/fips-hello-dep1.git
fips-hello-dep2 => https://github.com/floooh/fips-hello-dep2.git
fips-hello-dep3 => https://github.com/floooh/fips-hello-dep3.git
fips-polyvox => https://github.com/mgerhardy/fips-polyvox.git
fips-enet => https://github.com/mgerhardy/fips-enet.git
fips-simpleai => https://github.com/mgerhardy/fips-simpleai.git
fips-sauce => https://github.com/mgerhardy/fips-sauce
fips-bgfx => https://github.com/floooh/fips-bgfx.git
fips-remotery => https://github.com/floooh/fips-remotery.git
fips-accidentalnoise => https://github.com/mgerhardy/fips-accidentalnoise.git
fips-noisepp => https://github.com/mgerhardy/fips-noisepp.git
fips-googletest => https://github.com/mgerhardy/fips-googletest
fips-freetype2 => https://github.com/mgerhardy/fips-freetype2
fips-libnoise => https://github.com/mgerhardy/fips-libnoise
fips-lua => https://github.com/mgerhardy/fips-lua
fips-assimp => https://github.com/fungos/fips-assimp
fips-recast => https://github.com/fungos/fips-recast.git
fips-glew => https://github.com/fungos/fips-glew.git
fips-nanovg => https://github.com/fungos/fips-nanovg.git
fips-imgui => https://github.com/fungos/fips-imgui.git
fips-turbobadger => https://github.com/fungos/fips-turbobadger.git
fips-stb => https://github.com/fungos/fips-stb.git
fips-oui => https://github.com/fungos/fips-oui.git
fips-nlohmann-json => https://github.com/sgerbino/fips-nlohmann-json.git
=== settings:
  config: osx-xcode-debug (default value)
  target: None (default value)
  jobs: 12 (default value)
  local: off (default value)
  iosteam: None (default value)
=== exports:
project 'test' exports:
    nothing
=== imports:
project 'test' imports:
    nothing
=== targets:
  config: osx-xcode-debug
Traceback (most recent call last):
  File "/Users/samw3/prj/Play/test/./fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "/Users/samw3/prj/Play/fips/mod/fips.py", line 49, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "/Users/samw3/prj/Play/fips/verbs/list.py", line 178, in run
    list_targets(fips_dir, proj_dir, args[1:])
  File "/Users/samw3/prj/Play/fips/verbs/list.py", line 72, in list_targets
    type_targets = [tgt for tgt in targets if targets[tgt] == type]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
samw3 test $ 
```

**Comment by floooh** [comment]
Yep I can reproduce the problem with your repro steps. Thanks a lot.

TBH `fips init` has been neglected by me and probably has rotted a lot (as indicated by that `fips_finish` warning). 

I'll try to investigate the problem and find a fix some time over the next few days.

**Comment by floooh** [comment]
Scratch that, working on a quick fix now...

**Comment by floooh** [comment]
(whoops wrong button lol)

**Comment by floooh** [comment]
Ok, this should be fixed now. In a project that doesn't have targets yet (because the CMakeLists.txt file is empty), this is printed:

```
=== targets:
  config: osx-xcode-debug
    none
```

...and in an existing project (with targets) which has been cleaned:

```
=== targets:
  config: sapp-metal-osx-vscode-debug
    can't fetch project target list, please run 'fips gen' first!
```

I also removed the obsolete call to `fips_finish` from the cmake template file.

If it's still broken for you, please reopen this ticket, or if you stumble over another problem, please open a new ticket. Thanks again for filing the bug!
